# Site settings
title: "Project Tracker"
email: your-email@example.com
description: >-
  A simple, clean project tracker to monitor progress across
  personal projects, work initiatives, and learning goals.
baseurl: "/ProjectTracker" # Update this to match your repository name
url: "https://your-username.github.io" # Update with your GitHub username

# GitHub Pages theme
remote_theme: pages-themes/minimal@v0.2.0
plugins:
  - jekyll-remote-theme

# Theme customization
color-scheme: light

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
